# Настройки для автоматической генерации заметок к релизу (Release Notes)

changelog:
  exclude:
    labels:
      - duplicate
      - ignore-for-release
    authors:
      - web-flow
      - dependabot[bot]

  categories:
    - title: "Release contents"
      labels:
        - enhancement
        - major
  renderers:
    - |
        # Release contents:
        This release contains build of Yandex Music desktop app
          - version: 5.118.1
          - build for: x86_64 systems.
          - Name of package: yandexmusic-5.118.1-Inf.x86_64.rpm

        # Tests:
        Package tested on:
          - Fedora 43.

        # Release notes:
        Regular update.
