changelog:
  # 1. Говорим гитхабу включать абсолютно все коммиты, даже если нет PR
  categories:
    - title: "📦 Изменения"
      labels:
        - '*'

  # 2. Переопределяем логику вывода. Текст внутри блока подставится ВСЕГДА
  renderers:
    - - |
        This release contains build of Yandex Music desktop app version $version for x86_64 systems.
        Name of package: yandexmusic-$version-Inf.x86_64.rpm

        Package tested on Fedora 43.

        Release notes:
        Regular update.
